### ISSUE TITLE
Open Cash Drawer

### ISSUE THREAD

**Issue by lucashornung** [anastaciocintra/escpos-coffee#10]
Hey! First of all, I love this library, as it made my life a lot easier!
I was wondering though, could you provide sample code for opening the cash drawer? I am trying to use the pulsePin methode with an EPSON TM-T88V for that purpose, but can't seem to get it to work.

**Comment by anastaciocintra** [comment]
Hi lucashornung ,
thanks to your feedback
the name of function that you should use is pulsePin, but i can´t test it, because i do not have one cash-drawer.

Because of these issue,  I readed again the documentation and this function  have a problem (missing one character: 'p')
I opened one branch to fix this bug

**Comment by lucashornung** [comment]
Great, thanks! 
I just came up with a similar fix, right before I got your message.

My fix was to just add this line to the method:

write(112);

is p already a variable in the code?

**Comment by lucashornung** [comment]
Also, maybe as a bit of a follow up, is there a way to check the printer status(paper, if the drawer is open, etc.)? Else I could try to add one tomorrow.

**Comment by anastaciocintra** [comment]
fixed the method pusePin
one sample (on samples) can be found with name pulsePin ...
you can change time one and time two parameters and pin connector (2 or 5).

you can download on last release v1.0.5

I do not have one cash drawer hardware, please, let me know if it is working.

thank you

**Comment by anastaciocintra** [comment]
> Great, thanks!
> I just came up with a similar fix, right before I got your message.
> 
> My fix was to just add this line to the method:
> 
> write(112);
> 
> is p already a variable in the code?

good, is this working fine?

**Comment by anastaciocintra** [comment]
read #50
