### ISSUE TITLE
Get status of the printer

### ISSUE THREAD

**Issue by LuckyDucky583** [anastaciocintra/escpos-coffee#11]
Is there a command to get the status of the printer (online/offline), when the paper is ending or the paper is finished?

**Comment by anastaciocintra** [comment]
hi @lucashornung 
actually, we have only one stream to send data to the printer..
to do this, is need to have data flow on both directions, and i do not know if is possible one general structure for all printers (in esc-pos) or if is necessary specific implementation for each printer. All of these is new to me. Anny idea?

**Comment by talhamughal10** [comment]
Hi can any one guide me how to print the image in the center using the thermal printer. i am using 80mm paper with black copper USB thermal printer.
I am able to align the text in the center but i am keep on hitting different alignement to printer to center the image and i am stuck here. i have tried setting left margin, using horizontal tab, everyting that can give space to image if alignment is not working.

**Comment by anastaciocintra** [comment]
> Is there a command to get the status of the printer (online/offline), when the paper is ending or the paper is finished?

Hy @LuckyDucky583,
you can see one sample code at https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/UsbStatus
