### ISSUE TITLE
ESCPOS Image Printing Issue

### ISSUE THREAD

**Issue by talhamughal10** [anastaciocintra/escpos-coffee#30]
I am trying to follow the sample you have shared in escpos-coffee 3.0.0. i have integrated it successfull and i am able to print everything text,barcode .. but i am stuck in printing images becuse i am using it in android and java.awt.BufferedImage doesnot exist in android... in addition to read image, in example you have used ImageIO.read() i am unable to import its library. what should i do to solve this problem because i am stuck here.
 
i have also asked the question on stackoverflow nobody respond there at this link:
https://stackoverflow.com/questions/59576770/methodhandle-invoke-and-methodhandle-invokeexact-are-only-supported-starting-wit

Getting this error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

it will be your kind pleasure if you will help out me i am new to android app development.

**Comment by papuscoder** [comment]
Hi @talhamughal10,
I beleave that you can find the answer at issue #9 .... (Failed to import in android)

**Comment by talhamughal10** [comment]
@papuscoder thank you for your reply i have downloaded this sample to test for image printing but when i have loaded it tried to configure the gradle, but it show error for gradle version mine 5.4.1 i have searched on google for upgrading the gradle version ... then i upgraded the gradle version to 5.6.1 it then showed the error to update the **ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.** 
Although, my android studio is latest i have checked for updates as well but didn't find the way...

if i am trying to copy the files to my existing project to run this example then i am unable to locate this import com.github.anastaciocintra.escpos.image.CoffeeImage; in a project.

Can you please guide me how to resolve the issue to get the image printed. :)

Thank you in advance.

**Comment by anastaciocintra** [comment]
see https://github.com/anastaciocintra/escpos-coffee/issues/9#issuecomment-571699126
