### ISSUE TITLE
Add right and left alignment in one line

### ISSUE THREAD

**Issue by abdullo211** [anastaciocintra/escpos-coffee#37]
Can u add feature for reciept
`Melon-------1000`
 `Stawberry---800`
If use PrintModeStyle for justification we must enter text for change style details.

**Comment by anastaciocintra** [comment]
Hi @abdullo211,
I need more information about your wish.
can you send the piece of code or detail more your idea.

**Comment by abdullo211** [comment]
Hi @anastaciocintra,
Is it possible to put dynamic data as in a table:
`No------Name-----------qty`
` 1. ------Melon--------- 23`
` 2.------Stawberry------234`
or put text on left and right aligment in one line: 
` escpos.style.setJustification(EscPosConst.Justification.Left_Default)
 escpos.write(printModeStyle, "Left data")
 escpos.style.setJustification(EscPosConst.Justification.Right)
escpos.writeLF("Right data")`
and it will print as : 
|Left data `          ` Right data|

**Comment by anastaciocintra** [comment]
@abdullo211,
I guess that i kown what you want, 
and is easy to do ... 
Java have a good toolbox for this kind of task, for example, you can use String format:

output:
````text
+----------+----------+----------+
|      left|       mid|     right|
+----------+----------+----------+
|left      |mid       |right     |
+----------+----------+----------+
|123       |0000000123|       123|
+----------+----------+----------+
|1,23      |      1,23|0000001,23|
+----------+----------+----------+
````
Java code:
````java
public class FormatSample {
    void print(){
        System.out.printf("%s\n","+----------+----------+----------+");
        System.out.format("|%10s|%10s|%10s|\n", "left", "mid", "right");
        System.out.printf("%s\n","+----------+----------+----------+");
        System.out.format("|%-10s|%-10s|%-10s|\n", "left", "mid", "right");
        System.out.printf("%s\n","+----------+----------+----------+");
        System.out.format("|%-10d|%010d|%10d|\n", 123, 123, 123);
        System.out.printf("%s\n","+----------+----------+----------+");
        System.out.format("|%-10.2f|%10.2f|%010.2f|\n", 1.23, 1.23, 1.23);
        System.out.printf("%s\n","+----------+----------+----------+");
    }
    public static void main(String[] args) {
        FormatSample obj = new FormatSample();
        obj.print();
    }
}

````

**Comment by abdullo211** [comment]
This is also a good idea, thanks for the answer.
