### ISSUE TITLE
Datamatrix code is absent in BarCodeSystem enum

### ISSUE THREAD

**Issue by hereisalexius** [anastaciocintra/escpos-coffee#39]
Using your lib for printing simple tickets.
Need to print Datamatrix barcode in the end of ticket but cannot find implementation in BarCodeSystem.

It is posible that I confused with code-systems namings.

Please advise.

**Comment by anastaciocintra** [comment]
Hi @hereisalexius,
No, you aren't confused about names of Barcode System.
The Datamatrix isn't implemented yet...

Its because my printer haven't this feature. 

but Im opened for ideas.
If you have the  documentation, I can help you.
[], Marco

**Comment by anastaciocintra** [comment]
Hi @hereisalexius,
take a look on [BarcodeGen](https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/BarcodeGen)
