### ISSUE TITLE
Horizontal print

### ISSUE THREAD

**Issue by joao-moniz** [anastaciocintra/escpos-coffee#40]
Hello, I've been trying to make my printer, print a bank slip for a long time, but I can't use page mode, do you know any api or can you tell me how to do this ??

**Comment by anastaciocintra** [comment]
Hi @joao-moniz 

Tell more about your OP 
Is this linux? Windows ? Bsd?...
Is your printer matricial? Is it older model?

Can your printer print a simple line ? Or simple text on notepad?

**Comment by joao-moniz** [comment]
My application is for android and yes I can already print text and barcode. But vertically.
My printer is 80mm thermal model MTP-3

**Comment by anastaciocintra** [comment]
Ok, you need to rotate, but you does not have page mode on your printer... Am I right?

imho, one solution is to create one image, then print the image (jpg).

It can easily work with text and images, but In contrast, when you send the output to one bitmap (or image) you loose the escpos commands... Think about barcodes... 

I know, it is a hard solution, hopefully another idea or technique will appear.
