### ISSUE TITLE
qrcode lateral 

### ISSUE THREAD

**Issue by deividnn** [anastaciocintra/escpos-coffee#46]
boa noite, é possível colocar qrcode lado esquerdo e texto lado direito? tipo:

[QRCODE]   TEXTOTEXTOTEXTO
[QRCODE]   TEXTOTEXTOTEXTO
[QRCODE]   TEXTOTEXTOTEXTO

**Comment by anastaciocintra** [comment]
Pela Lib acho que não 
Mas se vc souber como fazer em escpos a gente pode implementar em parceria e vc pode ser um contributor..
Vamos tentar falar em língua inglesa aqui 
Se preferir 
Pode me mandar e-mail  
anastaciocintra@gmail.com

**Comment by deividnn** [comment]
Ok
