### ISSUE TITLE
i can't print Arabic letters , i use         escpos.setCharacterCodeTable(EscPos.CharacterCodeTable.CP864_Arabic);   but the output is only Chinese letters. 

### ISSUE THREAD

**Issue by M-Elnemr** [anastaciocintra/escpos-coffee#47]
## Steps to Reproduce

1. ...
2. ...
3. ...

```
```

**Comment by anastaciocintra** [comment]
Hi @M-Elnemr 
Other colleagues had the same question. Then I wrote a wiki with this theme that contain some tips for printer diagnosis and solutions.

Take a look at [wiki](https://github.com/anastaciocintra/escpos-coffee/wiki/Character-Code-Table) and count on me to answer the questions.

see you

**Comment by anastaciocintra** [comment]
one good issue history is #44

**Comment by M-Elnemr** [comment]
Socket sock = new Socket();
        sock.connect(new InetSocketAddress(PrinterConstants.IP, PrinterConstants.PORT), 1500);
        oStream = sock.getOutputStream();
        EscPos escpos = new EscPos(oStream);
        escpos.setPrinterCharacterTable(3);
        escpos.setCharsetName("860");
        escpos.writeLF("Some Portuguese special characters: çÇÃãõà");
        escpos.feed(5);
        escpos.cut(EscPos.CutMode.FULL);
        escpos.close();

this is my code as you mentioned in the documentation but unfortunately it print this part"çÇÃãõà" as Chinese letters 
idk maybe my printer has a problem

**Comment by anastaciocintra** [comment]
hi @M-Elnemr 
can you talk about your printer model and brand? 
Do you have the programming manual? can you send here ?

**Comment by anastaciocintra** [comment]
Hi @M-Elnemr,
is your problem solved? are you member of @ralmarri12 team? can I close this issue?
