### ISSUE TITLE
'0' Printing at the beginning of the line

### ISSUE THREAD

**Issue by wellnotanaccount** [anastaciocintra/escpos-coffee#55]
When printing using using writeLF(), '0' shows only at the beginning of the line and using write() it adds '0' at the start and end of the line. 
Any idea how to fix this?

![image](https://user-images.githubusercontent.com/21273252/98928260-8e2fc100-2514-11eb-8cb8-67be730df828.png)

When trying to System out it shows this

![image](https://user-images.githubusercontent.com/21273252/98928140-6a6c7b00-2514-11eb-89da-90531a161000.png)

**Comment by anastaciocintra** [comment]
hi @wellnotanaccount 
can you share your peace of code to reproduce this problem?

**Comment by wellnotanaccount** [comment]
Hello @anastaciocintra, I'm using the sample code.

```                
        PrintService printService = PrinterOutputStream.getPrintServiceByName("58 Printer");
        PrinterOutputStream printerOutputStream = new PrinterOutputStream(printService);
        EscPos escpos = new EscPos(System.out);

        escpos.writeLF("Test Test Test Test Test");
        escpos.write("Test Test Test Test Test");

        escpos.feed(5);
        escpos.cut(EscPos.CutMode.FULL);
        escpos.close();

        EscPos escpos1 = new EscPos(System.out);
        escpos1.writeLF("Test Test Test Test Test");
        escpos1.feed(5);
        escpos1.cut(EscPos.CutMode.FULL);
        escpos1.close();

**Comment by anastaciocintra** [comment]
It is printing well in mine printer (epson tm-t20)

![20201112_083015](https://user-images.githubusercontent.com/43155086/98935502-6152be00-24c2-11eb-87e0-54fd497f27ea.jpg)

maybe our printer doesn't have text style capabilities.  You can try another way to style the text.

```java
        PrintService printService = PrinterOutputStream.getPrintServiceByName("tm-t20-usb" );
        PrinterOutputStream printerOutputStream = new PrinterOutputStream(printService);
        EscPos escpos = new EscPos(printerOutputStream);

//        escpos.writeLF("Test Test Test Test Test");
//        escpos.write("Test Test Test Test Test");

        PrintModeStyle normal = new PrintModeStyle();
        escpos.writeLF(normal,"hello normal PrintModeStyle");
        PrintModeStyle rightBold = new PrintModeStyle().setBold(true).setJustification(EscPosConst.Justification.Right);
        escpos.writeLF(rightBold,"Right bold");
        escpos.feed(5).cut(EscPos.CutMode.FULL);
        escpos.close();

```

more on https://github.com/anastaciocintra/escpos-coffee/wiki/Text-Styles

I hope that it will work.
see you

**Comment by wellnotanaccount** [comment]
Weird, I ran the code you gave.. Normal Style works but not on the 2nd line(Right Bold)
I tried to style both lines with normal but 2nd line still shows '0' on the last next line.
``` 
 escpos.writeLF(normal,"hello normal PrintModeStyle");
 escpos.writeLF(normal,"Right bold"); 
```

![image](https://user-images.githubusercontent.com/21273252/98940818-86791800-2526-11eb-9b9d-c79698de4385.png)

I'm using [Rongta RP58](https://www.rongtatech.com/rp58a-58mm-thermal-receipt-printer_p71.html), the printer self-test shows normal. Not sure what is causing the '0'. 

I will try to experiment with styling, see if this will fix my issue. I'll update here. 

Thank you!

**Comment by anastaciocintra** [comment]
`weird.. I ran the code you gave.. Normal Style works but not on the 2nd line(Right Bold)
I tried to style both lines with normal but 2nd line still shows '0' on the last next line.`

I'm thinking here: it is one possible that your printer is printing zero when you send one cut,
it is because on cut(), the driver send ascii 48 '0'
and the printer doen't recognize the cut command (GS V command).

thest the code without cut...

```
        PrintService printService = PrinterOutputStream.getPrintServiceByName("tm-t20-usb" );
        PrinterOutputStream printerOutputStream = new PrinterOutputStream(printService);
        EscPos escpos = new EscPos(printerOutputStream);

//        escpos.writeLF("Test Test Test Test Test");
//        escpos.write("Test Test Test Test Test");

        PrintModeStyle normal = new PrintModeStyle();
        escpos.writeLF(normal,"hello normal PrintModeStyle");
        PrintModeStyle rightBold = new PrintModeStyle().setBold(true).setJustification(EscPosConst.Justification.Right);
        escpos.writeLF(rightBold,"Right bold");
        // change this line
//        escpos.feed(5).cut(EscPos.CutMode.FULL);
        // by this
        escpos.feed(15);
        escpos.close();
```

**Comment by wellnotanaccount** [comment]
![image](https://user-images.githubusercontent.com/21273252/99075021-bfcb8980-25f3-11eb-9368-311a6a876784.png)

even `feed(15);` also gives me zero but I was able to fix it by substituting escape `escpos.writeLF(normal,"\n\n\n");`

![image](https://user-images.githubusercontent.com/21273252/99075071-d1ad2c80-25f3-11eb-9ccb-3509651dc052.png)

PrintModeStyles works perfectly! Thank you very much @anastaciocintra!

**Comment by anastaciocintra** [comment]
good @wellnotanaccount 
count on me.
if you discover wich sequence is the cut on your printer send here.
