### ISSUE TITLE
BitonalOrderedDither crash

### ISSUE THREAD

**Issue by SerggioC** [anastaciocintra/escpos-coffee#59]
I dont know what kind of issue this should be in or why is it happening, but here it is.
I got this crash report on crashlytics log from BitonalOrderedDither:

```
Fatal Exception: java.lang.RuntimeException
Caused by java.lang.NoSuchMethodError
No virtual method ints(II)Ljava/util/stream/IntStream; in class Ljava/util/Random; or its super classes (declaration of 'java.util.Random' appears in /system/framework/core-libart.jar)
com.github.anastaciocintra.escpos.image.BitonalOrderedDither.<init> (BitonalOrderedDither.java:70)
com.github.anastaciocintra.escpos.image.BitonalOrderedDither.<init> (BitonalOrderedDither.java:84)

```

Any ideas what is?

Thank you!

**Comment by anastaciocintra** [comment]
No @SerggioC,

Is  this reproducible? Can you share the piece of code ?

**Comment by SerggioC** [comment]
Hi, 
This only happened once as it's reported by Firebase Crashlytics, this never occured in my tests.
Can't find out why the stacktrace refers Random and IntStream...

I have this code to print images:

```
                    RasterBitImageWrapper imageWrapper = new RasterBitImageWrapper();
                    Bitonal algorithm = new BitonalOrderedDither();
                    EscPosImage escposImage = new EscPosImage(new CoffeeImageAndroidImpl(bitmap), algorithm);
                    escposCoffeePrinter.write(imageWrapper, escposImage);
```

**Comment by anastaciocintra** [comment]
is this on android?

**Comment by SerggioC** [comment]
Yes it's on andoid.

**Comment by anastaciocintra** [comment]
ok, I've reproduced it wright now  on desenv / with api 19 kitkat. and api 21 too
I don't know why yet but it can work with threshold, an simplier algorithm

```
//            Bitonal algorithm = new BitonalThreshold();
            Bitonal algorithm = new BitonalOrderedDither();
```

I don't know the min api sdk version to espos-coffee work properly, need to test!
but 19 kitkat can work with this caveats (BitonalOrderedDither();)

**Comment by anastaciocintra** [comment]
change 
```
Bitonal algorithm = new BitonalOrderedDither();

```
by this
```
Bitonal algorithm = new BitonalThreshold();

```

**Comment by SerggioC** [comment]
Great catch! I will try the change.

As I see in the sample, using BitonalThreshold the resulted printed image will be smaller with "compacted" pixels right?
Is that the only difference?
I'm on min SDK 19 for the project.

Thank you.

**Comment by anastaciocintra** [comment]
good, 
19 is ok for me!
the difference between threshold and ordered diter is that with the ordered BitonalOrderedDither, the image printed have a grey-scale sensation for whom is seeing, and threshold algo print a image in black-white (more traditional way).   But the size of printing is the same.

I will focus on discover exactly witch android api/sdk min version is necessary for escpos-lib  (next activities).

**Comment by SerggioC** [comment]
Thanks @anastaciocintra.
I'll update the version. 
Until now, after changing to BitonalThreshold, I didn't see any more crashes.
Issue can be closed maybe.
