### ISSUE TITLE
set charsetname for WPC1252

### ISSUE THREAD

**Issue by awikatchikaen** [anastaciocintra/escpos-coffee#62]
Could you modify 
WPC1252(16)
by
WPC1252(16, "cp1252") ?

To avoid error between encoding encoding text and page used by the printer ?

For now, I do it with two lines :
document.setCharacterCodeTable(EscPos.CharacterCodeTable.WPC1252)
document.setCharsetName("cp1252") 

Thank you

**Comment by anastaciocintra** [comment]
hi @awikatchikaen ,
thanks for inform this bug.
I'll test it on next days.

**Comment by anastaciocintra** [comment]
It's fair that you participate as a contributor of this project.
for this you can fork / modify this point of the code and open a pull request..
but its up to you decide (let me know your decision).
If not, I'll make the correction.

see you!
