### ISSUE TITLE
necesito ayuda estoy tratando de imprimir una imagen pero me salen otros caracteres

### ISSUE THREAD

**Issue by anastaciocintra** [anastaciocintra/escpos-coffee#65]
necesito ayuda estoy tratando de imprimir una imagen pero me salen otros caracteres

_Originally posted by @JulioCesarQ in https://github.com/anastaciocintra/escpos-coffee/issues/44#issuecomment-812454804_

**Comment by anastaciocintra** [comment]
Hi @JulioCesarQ
Ok 
What is your printer brand and model?
Can you share the piece of code with problem ?

**Comment by JulioCesarQ** [comment]
modelo de impresora APT-AP300

Codigo
`try {
			PrintService printService = PrinterOutputStream.getPrintServiceByName("JM 9-pin printer wide");
			PrinterOutputStream printerOutputStream = new PrinterOutputStream(printService);
			EscPos escpos = new EscPos(printerOutputStream);
			//
			PDDocument document = PDDocument.load(ClassLoader.getSystemResourceAsStream(
					"archivo.pdf"));
			PDFRenderer pdfRenderer = new PDFRenderer(document);
			int nu = document.getNumberOfPages();

			for (int i = 0; i < nu; i++) {
				BufferedImage image = pdfRenderer.renderImage(i);

				new ImageHelper().write(escpos, new CoffeeImageImpl(image), new RasterBitImageWrapper(),
						new BitonalOrderedDither());
				escpos.feed(3).cut(EscPos.CutMode.PART);
			}
			 document.close();
			 // Style bold = new Style(escpos.getStyle())
			 // .setFontSize(Style.FontSize._8, Style.FontSize._8);
			 // escpos.writeLF(bold, "Coco 11");
			 // escpos.writeLF("Hello Wold");
			escpos.feed(5);
			escpos.cut(EscPos.CutMode.FULL);
			escpos.close();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}`

**Comment by anastaciocintra** [comment]
hi @JulioCesarQ ,
is this your printer? 
[https://apt-pos.com/impresora-matriz/38-apt-ap300.html](https://apt-pos.com/impresora-matriz/38-apt-ap300.html)

**Comment by JulioCesarQ** [comment]
si esa es la impresora Yes!

**Comment by anastaciocintra** [comment]
ok, this printer is compatible with ESC/P pattern and not totally compatible with ESC/POS

see, on "Especificaciones"
"Compatibilidad: EPSON LX 300."

and about EPSON LX 300:
[https://github.com/mike42/escpos-php/issues/871](https://github.com/mike42/escpos-php/issues/871)

In other words this library (escpos-coffee) isn't recommended to be used with APT-AP300.
