### ISSUE TITLE
Get response from escpos commands

### ISSUE THREAD

**Issue by tleveque** [anastaciocintra/escpos-coffee#67]
I am able to print all my tickets on my Oxhoo TP85.
Now, I would like to send commands to the printer to get status (out of paper...).
I found the escpos command (GS r 1) to send from Oxhoo documentation but I do not know how to receive the response using the API.
Is it possible ?
Thanks

**Comment by anastaciocintra** [comment]
Hi @tleveque,
Its not an ease answer, Its depends, I don't know how many methods exists, but this method worked for me. I didn't use it in production environment, It was just for fun to me. In other words, I didn't test exhaustively. 

> I found the escpos command (GS r 1) 

I've used `GS a`  command ( Automatic Status Back). Your printer's brand need to be able to respond the Automatic Status Back command;

> but I do not know how to receive the response using the API.

I've used one bi-directional I/O: USB or Serial Port. 


You can see the code at [UsbStatus](https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/UsbStatus) and [SerialStatus](https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous/SerialStatus)

Hope this helps.


![frame1](https://user-images.githubusercontent.com/43155086/122452341-8c811c80-cf7f-11eb-809a-07f9cd72a5ef.png)
![frame2](https://user-images.githubusercontent.com/43155086/122452368-930f9400-cf7f-11eb-83ac-e3bcb27031bd.png)

**Comment by tleveque** [comment]
Hi,
Thanks. I am able to get status from OXhoo TP85 by modifying a bit USBStatus example.
I needed to use zadig on Windows 10 and use following config instead of Epson one.
usbStatus = new UsbStatusTP85((short) 0x20d1,(short) 0x7009, (byte) 0x00, (byte) 0x02, (byte) 0x82);
