### ISSUE TITLE
Print for UNC

### ISSUE THREAD

**Issue by FelipeRodrigues21** [anastaciocintra/escpos-coffee#72]
Hey guys, how are you ? 
I need print receipt in my application java, but my prinnter was configured in formart UNC for windows and i need to know lib suport this is formart print?

**Comment by anastaciocintra** [comment]
hi @FelipeRodrigues21, good question!
is UNC a short for Universal Naming Convention? 
is your printer one "regular" thermal printer?

**Comment by FelipeRodrigues21** [comment]
@anastaciocintra Yes, but my printer is regular thermal printer, and my infractuture is limited, and i need share my printer in one computer. The lib has the printer for UNC ?

**Comment by anastaciocintra** [comment]
I think so ,
Did you test the samples?
https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/usual/getstart

IMHO it will list all installed printers on windows... 
Do you have maven?

**Comment by FelipeRodrigues21** [comment]
@anastaciocintra I don't have the test, because the printer was connected in other computer, your example work for printer was instaled in my computer and i am use maven.

**Comment by anastaciocintra** [comment]
Ok

Can you send me configuration by email anastaciocintra@gmail.com ?

**Comment by anastaciocintra** [comment]
@FelipeRodrigues21 
I found this link
May be can help ...

https://minisoft.com/support/index.php/print-to-a-unc-path-printer/

**Comment by FelipeRodrigues21** [comment]
@anastaciocintra i need this setup:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/7eb56b1f-d8f9-4366-aa0a-555c819e1bbf/constructing-printqueue-from-unc-path-using-c?forum=netfxbcl

**Comment by anastaciocintra** [comment]
Ok,
I've tested the Java print service with local printer, ip printer.,with cups and  bonjour... it worked well with all these configuration options.
But ,maybe  you need to install  remote printer on the local machine like a shared printer... then the java printservice can find your remote printer.

**Comment by FelipeRodrigues21** [comment]
Ok @anastaciocintra I will install the printer and my computer and use it.
Thank you for help me.
