### ISSUE TITLE
Failed to import in android

### ISSUE THREAD

**Issue by Zulqurnain** [anastaciocintra/escpos-coffee#9]
Unable to import this .jar into android project, can you please also make it android dependency?

**Comment by anastaciocintra** [comment]
Im not sure that it will work, but I´ll see it, 
please tell me, are you using android studio?

**Comment by Zulqurnain** [comment]
Yes I am using the android studio, I tried including it as .jar / external project but no use it uses BufferedImage rather than Bitmap which android doesn't compile

**Comment by anastaciocintra** [comment]
Are you testing other features on android Studio? Or testing image features are the unique ones that you are focusing? I need to know, because this (possible) version of the library for android need to be trusted.

**Comment by Zulqurnain** [comment]
I am importing this library in Android Studio

**Comment by JackNJack** [comment]
Can this already be used as android library? How?

**Comment by Muraveiko** [comment]
**1. repositories**
https://github.com/402d/RawBt-and-ESCPOS-coffee/blob/master/app/build.gradle#L2
**2. compileOptions**
https://github.com/402d/RawBt-and-ESCPOS-coffee/blob/master/app/build.gradle#L9
**3. implementation**  'com.github.anastaciocintra:escpos-coffee:2.0.0'

**Comment by derickfelix** [comment]
I believe it is now possible to import this project into an android app more easily with the new release which supports maven, and gradle.

**Comment by Muraveiko** [comment]
Big problem is import java.awt.image.* 

The library can be used in an android project only without a graphic part.
Printing pictures through the library is the most delicious part of it. Alas, unavailable.

**Comment by anastaciocintra** [comment]
yeap,
related to it.. https://github.com/anastaciocintra/escpos-coffee/issues/9#issuecomment-472401489
but it is possible (in thesis).
I'm thinking about the bether way to architect it .. Any Idea?

**Comment by anastaciocintra** [comment]
> Big problem is import java.awt.image.*
> 
> The library can be used in an android project only without a graphic part.
> Printing pictures through the library is the most delicious part of it. Alas, unavailable.



yeap,
related to it.. #9 (comment)
but it is possible (in thesis).
I'm thinking about the bether way to architect it .. Any Idea?

**Comment by Muraveiko** [comment]
Starting from this place, Android needs the Bitmap type
https://github.com/anastaciocintra/escpos-coffee/blob/master/escpos-coffee/src/main/java/com/github/anastaciocintra/escpos/image/EscPosImage.java#L30

Those. In fact, everything in the picture folder needs to be redone for analogues that are in android.
My opinion is only a separate version. If you try to do it universally, the library will lose its ease of use.

**Comment by anastaciocintra** [comment]
or create a specific repository (https://github.com/anastaciocintra/escpos-coffee/issues/9#issuecomment-538779847) like escpos-coffe-android (and sync it through patches from the original)
or divide the lib into 2 small pieces
I don't see elegant solution

**Comment by derickfelix** [comment]
This can help:
https://github.com/DantSu/PrinterThermal-ESCPOS-Android.

**Comment by anastaciocintra** [comment]
I made some changes on BRANCH ((((android)))) https://github.com/anastaciocintra/escpos-coffee.git
to work with Android(Bitmap) and traditional jdk(BufferedImage) (4.0.0-SNAPSHOT)

sample of use can be found on https://github.com/anastaciocintra/AdroidEscposCoffee.git

and u can run simple network print-service https://github.com/anastaciocintra/AdroidEscposCoffee.git

print image ok from Adroid app...

**Comment by emproducciones2257** [comment]
Saludos desde Argentina! estoy experimentando con Android y quisiera imprimir con esta libreria por una impresora USB, conocen algun proyecto para conectar una impresora USB? Saludos. Gran proyecto esta!!

**Comment by talhamughal10** [comment]
unable to load the  https://github.com/anastaciocintra/AdroidEscposCoffee.git project in my android studio it asked me to upgrade the gradle when i have tried to update the gradle it then asked me to upgrade the android studio 
**ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.**
when i am trying to load your files in my current running project with com.github.anastaciocintra:escpos-coffee:3.0.0 library added already.... i am unable to import the class with import com.github.anastaciocintra.escpos.image.CoffeeImage;
it doesnot located in the library which i have downloaded from your repository.

**Comment by anastaciocintra** [comment]
**Wich android studio version are you using? 
I'll try to compile with same version in my machine...**

### one tip:

It's important to use com.github.anastaciocintra:escpos-coffee:4.0.0-SNAPSHOT lib
SNAPSHOT (it's the same as unistable version) 

### ---->>>> MAYBE I'LL MAKE SOME CHANGES BEFORE THE RELEASE OR OFFICIAL VERSION

You can import this specific version of the library by configuring your app (build.gradle)
```gradle
...


repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}


dependencies {
    implementation 'com.github.anastaciocintra:escpos-coffee:4.0.0-SNAPSHOT'
}






...
``` 
And after that, I beleave that your project (with copied files) will work...

**Comment by anastaciocintra** [comment]
@talhamughal10,
In my Android Studio - 3.6 on Ubuntu get same ERROR message as on yours IDE, for me, the solution was change the line of classpath:

_Go to the menu File/Project Structure and / Project /_ 
Android Gradle Plugin Version 
Gradle Version
and change it...

**Comment by anastaciocintra** [comment]
> I made some changes on BRANCH ((((android)))) https://github.com/anastaciocintra/escpos-coffee.git
> to work with Android(Bitmap) and traditional jdk(BufferedImage) (4.0.0-SNAPSHOT)
> 
> sample of use can be found on https://github.com/anastaciocintra/AdroidEscposCoffee.git
> 
> and u can run simple network print-service https://github.com/anastaciocintra/server-print.git
> print image ok from Adroid app...


The sample code for printing images on android was moved to https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/miscellaneous 

and escpos-coffee was release to 4.0.1 on maven repo (officially)


the https://github.com/anastaciocintra/AdroidEscposCoffee.git and https://github.com/anastaciocintra/server-print.git will be deleted
